# Assignment-1 Machine Learning Lab
**RollNo: 101803186**, 
**Name: Kulpreet Singh**,
**Group: 3COE9**

In [189]:
import nltk

In [190]:
nltk.download('gutenberg')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [191]:
from nltk.corpus import gutenberg

In [192]:
gutenberg.words()

['[', 'Emma', 'by', 'Jane', 'Austen', '1816', ']', ...]

In [193]:
gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

#Q1: Load a corpus (of .txt files) of your choice containing at least 10 text files using:

**1. File Method**

In [194]:
#Loading my own corpus
import os
filenames=os.listdir('/content/drive/MyDrive/ownCorpus/')
contents=[]
for i in range(len(filenames)):
  f=open('/content/drive/MyDrive/ownCorpus/'+filenames[i],'r')
  text=f.read()
  contents.append(text)
  f.close()
contents

['Delhi MCD Election Results 2021 Live Updates: The Aam Aadmi Party (AAP) put on a good show in the five bye-elections to the Municipal Corporation of Delhi on Wednesday, winning four seats including Kalyanpuri, Rohini-C, Shalimar Bagh (North), and Trilokpuri. The Congress, on the other hand, won the Chauhan Banger ward.\n\nVoting was held in two wards — Rohini-C and Shalimar Bagh (North) — in the North Delhi Municipal Corporation (NDMC), and three wards — Trilokpuri, Kalyanpuri and Chauhan Banger — in the East Delhi Municipal Corporation (EDMC) last Sunday. While Shalimar Bagh (North) is reserved for women, Trilokpuri and Kalyanpuri are reserved for the Scheduled Caste (SC) category. The voter turnout recorded was 50.86 per cent.',
 'The ruling Aam Aadmi Party bagged four seats in Municipal Corporations of Delhi (MCD) bypolls on Tuesday. Following the sweeping victory, the AAP convener and Delhi chief minister, Arvind Kejriwal took to Twitter congratulate on the win. "The people of De

**2. PlaintextCorpusReader**

In [195]:
from nltk.corpus import PlaintextCorpusReader
dataset=PlaintextCorpusReader('/content/drive/MyDrive/ownCorpus/' ,'.*')

In [196]:
dataset

<PlaintextCorpusReader in '/content/drive/MyDrive/ownCorpus'>

In [197]:
dataset.fileids()

['AAP wins.txt',
 'BJP.txt',
 'Delhi Civic Bypolls.txt',
 'MCD elections.txt',
 'covid19.txt',
 'lenovo.txt',
 'maharashtra.txt',
 'oneplus.txt',
 'vaccine.txt',
 'west bengal.txt']

In [198]:
dataset.raw()

'The ruling Aam Aadmi Party bagged four seats in Municipal Corporations of Delhi (MCD) bypolls on Tuesday. Following the sweeping victory, the AAP convener and Delhi chief minister, Arvind Kejriwal took to Twitter congratulate on the win. "The people of Delhi once again voted in the name of work. Congratulations to everyone. The 15-year-old BJP\'s misrule in MCD has disturbed the people. People are now eager to form Aam Aadmi Party government in MCD also," he wrote on Twitter.\r\n\r\nDelhi deputy chief minister Manish Sisodia also congratulated the party workers on the micro-blogging site. "Congratulations to the Aam Aadmi Party workers on winning 4 out of 5 seats in the MCD by-election. In the municipal elections next year, people in Delhi will bring to power the AAP for its excellent governance model under Arvind Kejriwal," the AAP leader said.\r\n\r\nThe AAP won Rohini-C (Ward No 32N), Trilokpuri (Ward No 02E), Kalyanpuri (Ward 008-E) and Shalimar Bagh North (Ward No 62N); whille Co

In [199]:
dataset.sents()

[['The', 'ruling', 'Aam', 'Aadmi', 'Party', 'bagged', 'four', 'seats', 'in', 'Municipal', 'Corporations', 'of', 'Delhi', '(', 'MCD', ')', 'bypolls', 'on', 'Tuesday', '.'], ['Following', 'the', 'sweeping', 'victory', ',', 'the', 'AAP', 'convener', 'and', 'Delhi', 'chief', 'minister', ',', 'Arvind', 'Kejriwal', 'took', 'to', 'Twitter', 'congratulate', 'on', 'the', 'win', '.'], ...]

In [200]:
dataset.words()

['The', 'ruling', 'Aam', 'Aadmi', 'Party', 'bagged', ...]

#Q2: Pre-process the corpus loaded in step 1(apply normalization, tokenization, stopword removal, stemming)

In [201]:
# Normalization
corpus = contents
lower_corpus=[]
print(corpus)
for i in range(len(corpus)):
  lower_corpus.append(' '.join([word.lower() for word in corpus[i].split()]))
print(lower_corpus)

['Delhi MCD Election Results 2021 Live Updates: The Aam Aadmi Party (AAP) put on a good show in the five bye-elections to the Municipal Corporation of Delhi on Wednesday, winning four seats including Kalyanpuri, Rohini-C, Shalimar Bagh (North), and Trilokpuri. The Congress, on the other hand, won the Chauhan Banger ward.\n\nVoting was held in two wards — Rohini-C and Shalimar Bagh (North) — in the North Delhi Municipal Corporation (NDMC), and three wards — Trilokpuri, Kalyanpuri and Chauhan Banger — in the East Delhi Municipal Corporation (EDMC) last Sunday. While Shalimar Bagh (North) is reserved for women, Trilokpuri and Kalyanpuri are reserved for the Scheduled Caste (SC) category. The voter turnout recorded was 50.86 per cent.', 'The ruling Aam Aadmi Party bagged four seats in Municipal Corporations of Delhi (MCD) bypolls on Tuesday. Following the sweeping victory, the AAP convener and Delhi chief minister, Arvind Kejriwal took to Twitter congratulate on the win. "The people of Del

In [202]:
# tokenization
from nltk.tokenize import word_tokenize
tokenized_corpus=[]
for i in range(len(lower_corpus)):
  tokenized_corpus.append([word for word in word_tokenize(lower_corpus[i]) if word.isalpha()] )
print(tokenized_corpus)

[['delhi', 'mcd', 'election', 'results', 'live', 'updates', 'the', 'aam', 'aadmi', 'party', 'aap', 'put', 'on', 'a', 'good', 'show', 'in', 'the', 'five', 'to', 'the', 'municipal', 'corporation', 'of', 'delhi', 'on', 'wednesday', 'winning', 'four', 'seats', 'including', 'kalyanpuri', 'shalimar', 'bagh', 'north', 'and', 'trilokpuri', 'the', 'congress', 'on', 'the', 'other', 'hand', 'won', 'the', 'chauhan', 'banger', 'ward', 'voting', 'was', 'held', 'in', 'two', 'wards', 'and', 'shalimar', 'bagh', 'north', 'in', 'the', 'north', 'delhi', 'municipal', 'corporation', 'ndmc', 'and', 'three', 'wards', 'trilokpuri', 'kalyanpuri', 'and', 'chauhan', 'banger', 'in', 'the', 'east', 'delhi', 'municipal', 'corporation', 'edmc', 'last', 'sunday', 'while', 'shalimar', 'bagh', 'north', 'is', 'reserved', 'for', 'women', 'trilokpuri', 'and', 'kalyanpuri', 'are', 'reserved', 'for', 'the', 'scheduled', 'caste', 'sc', 'category', 'the', 'voter', 'turnout', 'recorded', 'was', 'per', 'cent'], ['the', 'ruling',

In [203]:
# Normalization and Tokenization using PlaintextCorpusReader .words()
tokenized_corpus2=[]
for i in range(len(dataset.fileids())):
  tokenized_corpus2.append([word.lower() for word in dataset.words(dataset.fileids()[i]) if word.isalpha()])
print(tokenized_corpus2)

[['the', 'ruling', 'aam', 'aadmi', 'party', 'bagged', 'four', 'seats', 'in', 'municipal', 'corporations', 'of', 'delhi', 'mcd', 'bypolls', 'on', 'tuesday', 'following', 'the', 'sweeping', 'victory', 'the', 'aap', 'convener', 'and', 'delhi', 'chief', 'minister', 'arvind', 'kejriwal', 'took', 'to', 'twitter', 'congratulate', 'on', 'the', 'win', 'the', 'people', 'of', 'delhi', 'once', 'again', 'voted', 'in', 'the', 'name', 'of', 'work', 'congratulations', 'to', 'everyone', 'the', 'year', 'old', 'bjp', 's', 'misrule', 'in', 'mcd', 'has', 'disturbed', 'the', 'people', 'people', 'are', 'now', 'eager', 'to', 'form', 'aam', 'aadmi', 'party', 'government', 'in', 'mcd', 'also', 'he', 'wrote', 'on', 'twitter', 'delhi', 'deputy', 'chief', 'minister', 'manish', 'sisodia', 'also', 'congratulated', 'the', 'party', 'workers', 'on', 'the', 'micro', 'blogging', 'site', 'congratulations', 'to', 'the', 'aam', 'aadmi', 'party', 'workers', 'on', 'winning', 'out', 'of', 'seats', 'in', 'the', 'mcd', 'by', 'el

In [204]:
# stopwords removal
from nltk.corpus import stopwords
stop=stopwords.words(fileids='english')
tokenized_corpus_nostop=[]
for i in range(len(tokenized_corpus)):
  tokenized_corpus_nostop.append([word for word in tokenized_corpus[i] if word not in stop])
print(tokenized_corpus_nostop)

[['delhi', 'mcd', 'election', 'results', 'live', 'updates', 'aam', 'aadmi', 'party', 'aap', 'put', 'good', 'show', 'five', 'municipal', 'corporation', 'delhi', 'wednesday', 'winning', 'four', 'seats', 'including', 'kalyanpuri', 'shalimar', 'bagh', 'north', 'trilokpuri', 'congress', 'hand', 'chauhan', 'banger', 'ward', 'voting', 'held', 'two', 'wards', 'shalimar', 'bagh', 'north', 'north', 'delhi', 'municipal', 'corporation', 'ndmc', 'three', 'wards', 'trilokpuri', 'kalyanpuri', 'chauhan', 'banger', 'east', 'delhi', 'municipal', 'corporation', 'edmc', 'last', 'sunday', 'shalimar', 'bagh', 'north', 'reserved', 'women', 'trilokpuri', 'kalyanpuri', 'reserved', 'scheduled', 'caste', 'sc', 'category', 'voter', 'turnout', 'recorded', 'per', 'cent'], ['ruling', 'aam', 'aadmi', 'party', 'bagged', 'four', 'seats', 'municipal', 'corporations', 'delhi', 'mcd', 'bypolls', 'tuesday', 'following', 'sweeping', 'victory', 'aap', 'convener', 'delhi', 'chief', 'minister', 'arvind', 'kejriwal', 'took', 't

In [205]:
# stemming
from nltk.stem import PorterStemmer
ps=PorterStemmer()
tokenized_corpus_nostop_stem=[]
for i in range(len(tokenized_corpus_nostop)):
  tokenized_corpus_nostop_stem.append([ps.stem(word) for word in tokenized_corpus_nostop[i]])
print(tokenized_corpus_nostop_stem)

[['delhi', 'mcd', 'elect', 'result', 'live', 'updat', 'aam', 'aadmi', 'parti', 'aap', 'put', 'good', 'show', 'five', 'municip', 'corpor', 'delhi', 'wednesday', 'win', 'four', 'seat', 'includ', 'kalyanpuri', 'shalimar', 'bagh', 'north', 'trilokpuri', 'congress', 'hand', 'chauhan', 'banger', 'ward', 'vote', 'held', 'two', 'ward', 'shalimar', 'bagh', 'north', 'north', 'delhi', 'municip', 'corpor', 'ndmc', 'three', 'ward', 'trilokpuri', 'kalyanpuri', 'chauhan', 'banger', 'east', 'delhi', 'municip', 'corpor', 'edmc', 'last', 'sunday', 'shalimar', 'bagh', 'north', 'reserv', 'women', 'trilokpuri', 'kalyanpuri', 'reserv', 'schedul', 'cast', 'sc', 'categori', 'voter', 'turnout', 'record', 'per', 'cent'], ['rule', 'aam', 'aadmi', 'parti', 'bag', 'four', 'seat', 'municip', 'corpor', 'delhi', 'mcd', 'bypol', 'tuesday', 'follow', 'sweep', 'victori', 'aap', 'conven', 'delhi', 'chief', 'minist', 'arvind', 'kejriw', 'took', 'twitter', 'congratul', 'win', 'peopl', 'delhi', 'vote', 'name', 'work', 'cong

In [206]:
# lemmatization
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer() 
tokenized_corpus_nostop_lemmatized=[]
for i in range(len(tokenized_corpus_nostop)):
  tokenized_corpus_nostop_lemmatized.append([lemmatizer.lemmatize(word) for word in tokenized_corpus_nostop[i]])
print(tokenized_corpus_nostop_lemmatized)

[['delhi', 'mcd', 'election', 'result', 'live', 'update', 'aam', 'aadmi', 'party', 'aap', 'put', 'good', 'show', 'five', 'municipal', 'corporation', 'delhi', 'wednesday', 'winning', 'four', 'seat', 'including', 'kalyanpuri', 'shalimar', 'bagh', 'north', 'trilokpuri', 'congress', 'hand', 'chauhan', 'banger', 'ward', 'voting', 'held', 'two', 'ward', 'shalimar', 'bagh', 'north', 'north', 'delhi', 'municipal', 'corporation', 'ndmc', 'three', 'ward', 'trilokpuri', 'kalyanpuri', 'chauhan', 'banger', 'east', 'delhi', 'municipal', 'corporation', 'edmc', 'last', 'sunday', 'shalimar', 'bagh', 'north', 'reserved', 'woman', 'trilokpuri', 'kalyanpuri', 'reserved', 'scheduled', 'caste', 'sc', 'category', 'voter', 'turnout', 'recorded', 'per', 'cent'], ['ruling', 'aam', 'aadmi', 'party', 'bagged', 'four', 'seat', 'municipal', 'corporation', 'delhi', 'mcd', 'bypolls', 'tuesday', 'following', 'sweeping', 'victory', 'aap', 'convener', 'delhi', 'chief', 'minister', 'arvind', 'kejriwal', 'took', 'twitter'

In [207]:
# cleaned corpus obtained after pre-processing
cleaned_corpus = []
for i in range(len(tokenized_corpus_nostop_lemmatized)):
  cleaned_corpus.append(' '.join([word for word in tokenized_corpus_nostop_lemmatized[i]]))
print(cleaned_corpus)

['delhi mcd election result live update aam aadmi party aap put good show five municipal corporation delhi wednesday winning four seat including kalyanpuri shalimar bagh north trilokpuri congress hand chauhan banger ward voting held two ward shalimar bagh north north delhi municipal corporation ndmc three ward trilokpuri kalyanpuri chauhan banger east delhi municipal corporation edmc last sunday shalimar bagh north reserved woman trilokpuri kalyanpuri reserved scheduled caste sc category voter turnout recorded per cent', 'ruling aam aadmi party bagged four seat municipal corporation delhi mcd bypolls tuesday following sweeping victory aap convener delhi chief minister arvind kejriwal took twitter congratulate win people delhi voted name work congratulation everyone bjp misrule mcd disturbed people people eager form aam aadmi party government mcd also wrote twitter delhi deputy chief minister manish sisodia also congratulated party worker site congratulation aam aadmi party worker winni

# Q3: Convert the corpus into Bag-of-Words and tf-idf feature matrix using:

**(a) TfidfVectorizer() and CountVectorizer()**

In [208]:
# Bag of Words matrix using CountVectorizer()
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(cleaned_corpus)
print(vectorizer.get_feature_names())
print(x.toarray())

['aadmi', 'aam', 'aap', 'abandoned', 'abhishek', 'according', 'accusing', 'acquisition', 'added', 'adhanom', 'adhere', 'adhir', 'african', 'ahmad', 'aimed', 'ajit', 'allegation', 'allying', 'already', 'also', 'anand', 'angola', 'angry', 'announced', 'announcement', 'appeared', 'appraisal', 'around', 'arvind', 'asked', 'assembly', 'associated', 'astrazeneca', 'back', 'bagged', 'bagh', 'banerjee', 'bangar', 'banger', 'base', 'began', 'begin', 'begun', 'benchmarking', 'bengal', 'bharatiya', 'bjp', 'breaching', 'bring', 'budget', 'buffer', 'built', 'bypolls', 'cambodia', 'campaign', 'candidate', 'capacity', 'cast', 'caste', 'catch', 'category', 'cent', 'centre', 'challenger', 'charge', 'chaudhary', 'chauhan', 'chief', 'chipset', 'chowdhury', 'city', 'cleric', 'club', 'codename', 'codenamed', 'come', 'comfortable', 'commitment', 'company', 'conducted', 'conference', 'confirmed', 'congo', 'congratulate', 'congratulated', 'congratulation', 'congress', 'congressman', 'consecutive', 'conserve',

In [209]:
# tfidf matrix using TfidfVectorizer()
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfvectorizer = TfidfVectorizer()
X = tfidfvectorizer.fit_transform(cleaned_corpus)
print(tfidfvectorizer.get_feature_names())
print(X.toarray())

['aadmi', 'aam', 'aap', 'abandoned', 'abhishek', 'according', 'accusing', 'acquisition', 'added', 'adhanom', 'adhere', 'adhir', 'african', 'ahmad', 'aimed', 'ajit', 'allegation', 'allying', 'already', 'also', 'anand', 'angola', 'angry', 'announced', 'announcement', 'appeared', 'appraisal', 'around', 'arvind', 'asked', 'assembly', 'associated', 'astrazeneca', 'back', 'bagged', 'bagh', 'banerjee', 'bangar', 'banger', 'base', 'began', 'begin', 'begun', 'benchmarking', 'bengal', 'bharatiya', 'bjp', 'breaching', 'bring', 'budget', 'buffer', 'built', 'bypolls', 'cambodia', 'campaign', 'candidate', 'capacity', 'cast', 'caste', 'catch', 'category', 'cent', 'centre', 'challenger', 'charge', 'chaudhary', 'chauhan', 'chief', 'chipset', 'chowdhury', 'city', 'cleric', 'club', 'codename', 'codenamed', 'come', 'comfortable', 'commitment', 'company', 'conducted', 'conference', 'confirmed', 'congo', 'congratulate', 'congratulated', 'congratulation', 'congress', 'congressman', 'consecutive', 'conserve',

**(b) Without using in-built functions**

In [210]:
features = []
for i in range(len(cleaned_corpus)):
  for word in cleaned_corpus[i].split():
    if word not in features:
      features.append(word)
features.sort()
print(len(features))
print(features)

376
['aadmi', 'aam', 'aap', 'abandoned', 'abhishek', 'according', 'accusing', 'acquisition', 'added', 'adhanom', 'adhere', 'adhir', 'african', 'ahmad', 'aimed', 'ajit', 'allegation', 'allying', 'already', 'also', 'anand', 'angola', 'angry', 'announced', 'announcement', 'appeared', 'appraisal', 'around', 'arvind', 'asked', 'assembly', 'associated', 'astrazeneca', 'back', 'bagged', 'bagh', 'banerjee', 'bangar', 'banger', 'base', 'began', 'begin', 'begun', 'benchmarking', 'bengal', 'bharatiya', 'bjp', 'breaching', 'bring', 'budget', 'buffer', 'built', 'bypolls', 'c', 'cambodia', 'campaign', 'candidate', 'capacity', 'cast', 'caste', 'catch', 'category', 'cent', 'centre', 'challenger', 'charge', 'chaudhary', 'chauhan', 'chief', 'chipset', 'chowdhury', 'city', 'cleric', 'club', 'codename', 'codenamed', 'come', 'comfortable', 'commitment', 'company', 'conducted', 'conference', 'confirmed', 'congo', 'congratulate', 'congratulated', 'congratulation', 'congress', 'congressman', 'consecutive', 'c

In [211]:
# Bag of words without using inbuilt function
import numpy as np

bow = np.zeros((len(cleaned_corpus), len(features)))
for i in range(len(cleaned_corpus)):
  for j in range(len(features)):
    bow[i][j] = cleaned_corpus[i].split().count(features[j])
print(bow)

[[1. 1. 1. ... 0. 0. 0.]
 [3. 3. 4. ... 1. 0. 1.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [212]:
# calculating idf matrix
idf = np.zeros(len(features))
df = np.zeros(len(features))
n = len(cleaned_corpus)
for i in range(len(features)):
  df[i] = 0
  for j in range(len(cleaned_corpus)):
    if features[i] in cleaned_corpus[j].split():
      df[i] += 1
  idf[i] = np.log((1+n)/(1+df[i])) + 1
print(len(idf))
print(idf)

376
[2.29928298 2.29928298 2.01160091 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.01160091 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.29928298 2.70474809 2.70474809 2.70474809 2.70474809 2.01160091
 2.70474809 2.70474809 2.29928298 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.29928298 2.70474809 2.29928298 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.29928298 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.29928298 2.01160091 2.70474809 2.70474809 2.70474809
 2.70474809 2.01160091 1.78845736 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 1.6061358  2.70474809 2.

In [213]:
# calculating tfidf matrix
tfidf = np.multiply(bow, idf)
print(tfidf)

[[2.29928298 2.29928298 2.01160091 ... 0.         0.         0.        ]
 [6.89784895 6.89784895 8.04640365 ... 2.29928298 0.         2.70474809]
 [0.         0.         4.02320182 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         2.70474809 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 2.29928298 0.         0.        ]]


In [214]:
# normalizing the tfidf matrix
import math
for i in range(len(tfidf)):
  count = 0
  for j in range(len(tfidf[i])):
    count += pow(tfidf[i][j], 2)
  count = math.sqrt(count)
  for j in range(len(tfidf[i])):
    tfidf[i][j] = tfidf[i][j]/count

print(tfidf)

[[0.08842085 0.08842085 0.07735779 ... 0.         0.         0.        ]
 [0.20829713 0.20829713 0.2429805  ... 0.06943238 0.         0.08167637]
 [0.         0.         0.2147997  ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.09720205 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.11757966 0.         0.        ]]


In [215]:
# tfidf matrix using TfidfVectorizer() for comparison
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfvectorizer = TfidfVectorizer()
X = tfidfvectorizer.fit_transform(cleaned_corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['aadmi', 'aam', 'aap', 'abandoned', 'abhishek', 'according', 'accusing', 'acquisition', 'added', 'adhanom', 'adhere', 'adhir', 'african', 'ahmad', 'aimed', 'ajit', 'allegation', 'allying', 'already', 'also', 'anand', 'angola', 'angry', 'announced', 'announcement', 'appeared', 'appraisal', 'around', 'arvind', 'asked', 'assembly', 'associated', 'astrazeneca', 'back', 'bagged', 'bagh', 'banerjee', 'bangar', 'banger', 'base', 'began', 'begin', 'begun', 'benchmarking', 'bengal', 'bharatiya', 'bjp', 'breaching', 'bring', 'budget', 'buffer', 'built', 'bypolls', 'cambodia', 'campaign', 'candidate', 'capacity', 'cast', 'caste', 'catch', 'category', 'cent', 'centre', 'challenger', 'charge', 'chaudhary', 'chauhan', 'chief', 'chipset', 'chowdhury', 'city', 'cleric', 'club', 'codename', 'codenamed', 'come', 'comfortable', 'commitment', 'company', 'conducted', 'conference', 'confirmed', 'congo', 'congratulate', 'congratulated', 'congratulation', 'congress', 'congressman', 'consecutive', 'conserve',

# Q4: Explore how we can access, pre-process and create feature vector for HTML texts?

In [216]:
html_doc = ["""
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
""", 
"""
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

</style>
</head>
<body>
On UTF-8 encoded pages, <wbr> behaves like the U+200B ZERO-WIDTH SPACE code point. 
In particular, it behaves like a Unicode bidi BN code point, meaning it has no effect on bidi-ordering: 
<div dir=rtl>123,<wbr>456</div> displays, when not broken on two lines, 123,456 and not 456,123.

For the same reason, the <wbr> element does not introduce a hyphen at the line break point.
 To make a hyphen appear only at the end of a line, use the soft hyphen character entity (&shy;) instead.
<h1>My Website</h1>
<p>A website created by me.</p>
Lilly was a little girl, castle of walls.
Life is good.
</body>
</html>
""",
"""
<!DOCTYPE html>
<html lang="en">
<head>
<title>Page Title</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

</style>
</head>
<body>
<p>The function <code>selectAll()</code> highlights all the text in the
input field so the user can, for example, copy or delete the text.</p>
<h1>My Bad</h1>
<p>can't find anything better.</p>
How can I be this silly, but it doesn't matter anyway, Hahah 
</body>
</html>
""" ]

In [217]:
# acccessing html data
import bs4
from bs4 import BeautifulSoup
html_data = []

for i in range(len(html_doc)):
  soup = BeautifulSoup(html_doc[i], 'html.parser')
  html_data.append(soup.get_text())

html_data

["\nThe Dormouse's story\n\nThe Dormouse's story\nOnce upon a time there were three little sisters; and their names were\nElsie,\nLacie and\nTillie;\nand they lived at the bottom of a well.\n...\n",
 '\n\n\n\nPage Title\n\n\n\n\n\n\nOn UTF-8 encoded pages,  behaves like the U+200B ZERO-WIDTH SPACE code point. \nIn particular, it behaves like a Unicode bidi BN code point, meaning it has no effect on bidi-ordering: \n123,456 displays, when not broken on two lines, 123,456 and not 456,123.\n\nFor the same reason, the  element does not introduce a hyphen at the line break point.\n To make a hyphen appear only at the end of a line, use the soft hyphen character entity (\xad) instead.\nMy Website\nA website created by me.\nLilly was a little girl, castle of walls.\nLife is good.\n\n\n',
 "\n\n\n\nPage Title\n\n\n\n\n\n\nThe function selectAll() highlights all the text in the\ninput field so the user can, for example, copy or delete the text.\nMy Bad\ncan't find anything better.\nHow can I be

In [218]:
# Normalization
corpus = html_data
lower_corpus=[]
print(corpus)
for i in range(len(corpus)):
  lower_corpus.append(' '.join([word.lower() for word in corpus[i].split()]))
print(lower_corpus)

["\nThe Dormouse's story\n\nThe Dormouse's story\nOnce upon a time there were three little sisters; and their names were\nElsie,\nLacie and\nTillie;\nand they lived at the bottom of a well.\n...\n", '\n\n\n\nPage Title\n\n\n\n\n\n\nOn UTF-8 encoded pages,  behaves like the U+200B ZERO-WIDTH SPACE code point. \nIn particular, it behaves like a Unicode bidi BN code point, meaning it has no effect on bidi-ordering: \n123,456 displays, when not broken on two lines, 123,456 and not 456,123.\n\nFor the same reason, the  element does not introduce a hyphen at the line break point.\n To make a hyphen appear only at the end of a line, use the soft hyphen character entity (\xad) instead.\nMy Website\nA website created by me.\nLilly was a little girl, castle of walls.\nLife is good.\n\n\n', "\n\n\n\nPage Title\n\n\n\n\n\n\nThe function selectAll() highlights all the text in the\ninput field so the user can, for example, copy or delete the text.\nMy Bad\ncan't find anything better.\nHow can I be t

In [219]:
# tokenization
from nltk.tokenize import word_tokenize
tokenized_corpus=[]
for i in range(len(lower_corpus)):
  tokenized_corpus.append([word for word in word_tokenize(lower_corpus[i]) if word.isalpha()] )
print(tokenized_corpus)

[['the', 'dormouse', 'story', 'the', 'dormouse', 'story', 'once', 'upon', 'a', 'time', 'there', 'were', 'three', 'little', 'sisters', 'and', 'their', 'names', 'were', 'elsie', 'lacie', 'and', 'tillie', 'and', 'they', 'lived', 'at', 'the', 'bottom', 'of', 'a', 'well'], ['page', 'title', 'on', 'encoded', 'pages', 'behaves', 'like', 'the', 'space', 'code', 'point', 'in', 'particular', 'it', 'behaves', 'like', 'a', 'unicode', 'bidi', 'bn', 'code', 'point', 'meaning', 'it', 'has', 'no', 'effect', 'on', 'displays', 'when', 'not', 'broken', 'on', 'two', 'lines', 'and', 'not', 'for', 'the', 'same', 'reason', 'the', 'element', 'does', 'not', 'introduce', 'a', 'hyphen', 'at', 'the', 'line', 'break', 'point', 'to', 'make', 'a', 'hyphen', 'appear', 'only', 'at', 'the', 'end', 'of', 'a', 'line', 'use', 'the', 'soft', 'hyphen', 'character', 'entity', 'instead', 'my', 'website', 'a', 'website', 'created', 'by', 'me', 'lilly', 'was', 'a', 'little', 'girl', 'castle', 'of', 'walls', 'life', 'is', 'good'

In [220]:
# stopwords removal
from nltk.corpus import stopwords
stop=stopwords.words(fileids='english')
tokenized_corpus_nostop=[]
for i in range(len(tokenized_corpus)):
  tokenized_corpus_nostop.append([word for word in tokenized_corpus[i] if word not in stop])
print(tokenized_corpus_nostop)

[['dormouse', 'story', 'dormouse', 'story', 'upon', 'time', 'three', 'little', 'sisters', 'names', 'elsie', 'lacie', 'tillie', 'lived', 'bottom', 'well'], ['page', 'title', 'encoded', 'pages', 'behaves', 'like', 'space', 'code', 'point', 'particular', 'behaves', 'like', 'unicode', 'bidi', 'bn', 'code', 'point', 'meaning', 'effect', 'displays', 'broken', 'two', 'lines', 'reason', 'element', 'introduce', 'hyphen', 'line', 'break', 'point', 'make', 'hyphen', 'appear', 'end', 'line', 'use', 'soft', 'hyphen', 'character', 'entity', 'instead', 'website', 'website', 'created', 'lilly', 'little', 'girl', 'castle', 'walls', 'life', 'good'], ['page', 'title', 'function', 'selectall', 'highlights', 'text', 'input', 'field', 'user', 'example', 'copy', 'delete', 'text', 'bad', 'ca', 'find', 'anything', 'better', 'silly', 'matter', 'anyway', 'hahah']]


In [221]:
# lemmatization
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer() 
tokenized_corpus_nostop_lemmatized=[]
for i in range(len(tokenized_corpus_nostop)):
  tokenized_corpus_nostop_lemmatized.append([lemmatizer.lemmatize(word) for word in tokenized_corpus_nostop[i]])
print(tokenized_corpus_nostop_lemmatized)

[['dormouse', 'story', 'dormouse', 'story', 'upon', 'time', 'three', 'little', 'sister', 'name', 'elsie', 'lacie', 'tillie', 'lived', 'bottom', 'well'], ['page', 'title', 'encoded', 'page', 'behaves', 'like', 'space', 'code', 'point', 'particular', 'behaves', 'like', 'unicode', 'bidi', 'bn', 'code', 'point', 'meaning', 'effect', 'display', 'broken', 'two', 'line', 'reason', 'element', 'introduce', 'hyphen', 'line', 'break', 'point', 'make', 'hyphen', 'appear', 'end', 'line', 'use', 'soft', 'hyphen', 'character', 'entity', 'instead', 'website', 'website', 'created', 'lilly', 'little', 'girl', 'castle', 'wall', 'life', 'good'], ['page', 'title', 'function', 'selectall', 'highlight', 'text', 'input', 'field', 'user', 'example', 'copy', 'delete', 'text', 'bad', 'ca', 'find', 'anything', 'better', 'silly', 'matter', 'anyway', 'hahah']]


In [222]:
# creating feature vector
features = []
for i in range(len(tokenized_corpus_nostop_lemmatized)):
  for word in tokenized_corpus_nostop_lemmatized[i]:
    if word not in features:
      features.append(word)
features.sort()
print(len(features))
print(features)

72
['anything', 'anyway', 'appear', 'bad', 'behaves', 'better', 'bidi', 'bn', 'bottom', 'break', 'broken', 'ca', 'castle', 'character', 'code', 'copy', 'created', 'delete', 'display', 'dormouse', 'effect', 'element', 'elsie', 'encoded', 'end', 'entity', 'example', 'field', 'find', 'function', 'girl', 'good', 'hahah', 'highlight', 'hyphen', 'input', 'instead', 'introduce', 'lacie', 'life', 'like', 'lilly', 'line', 'little', 'lived', 'make', 'matter', 'meaning', 'name', 'page', 'particular', 'point', 'reason', 'selectall', 'silly', 'sister', 'soft', 'space', 'story', 'text', 'three', 'tillie', 'time', 'title', 'two', 'unicode', 'upon', 'use', 'user', 'wall', 'website', 'well']
